version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./js_examples:/app/static/js_examples
      - ./aurelia:/app/src
    ports:
      - 8080:8080

# docker compose up -d --build
# in the container to compile again: au build
